### PR TITLE
Usability

### PR DESCRIPTION
**Pull request by jeremybobbin**
- Batch Sizes are chosen based on VRAM in the machine
- Tensorflow Benchmarks submodules are initialized when `benchmark.sh` is run
- Eliminate need for `expect` depency with `python3 -u`. `unbuffer` can also be replaced by `stdbuf -iL -oL -eL`
- Metadata file. This may look like:
 
```
Memory  15.3551GB
GPU 0   GeForce RTX 2070 with Max-Q Design
CPU     i7-8750H
CUDA    V10.0.130
Nvidia  440.64
TF      1.15.2
Kernel  5.3.0-46-generic
Python  3.6.9
```

### CODE REVIEW

**Comment by ityonemo** [comment]
♥️

**Comment by sclarkson** [comment]
@chuanli11

**Comment by chuanli11** [comment]
Thank you Jeremy!

**Comment by chuanli11** [comment]
Thank you @jeremybobbin

**Pull request merged**
